-- Live schema contract for SHELLHACKS_DB.STORY_MODE.
-- This file records the definitions used by the backend and team pipelines.

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.PRICE_HISTORY (
  SYMBOL VARCHAR(16) NOT NULL, TRADE_DATE DATE NOT NULL,
  CLOSE_PRICE NUMBER(18,4) NOT NULL, DAILY_RETURN_PCT NUMBER(10,4),
  DATA_SOURCE VARCHAR(100), INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SYMBOL, TRADE_DATE)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.STORY_EVENTS (
  EVENT_ID VARCHAR(36) DEFAULT UUID_STRING(), SYMBOL VARCHAR(16) NOT NULL,
  EVENT_DATE DATE NOT NULL, HEADLINE VARCHAR NOT NULL, SUMMARY VARCHAR NOT NULL,
  PRICE_MOVE_PCT NUMBER(10,4), EVENT_TYPE VARCHAR(50) NOT NULL, SOURCE_URL VARCHAR,
  DATA_CONFIDENCE NUMBER(3,2) DEFAULT 1.00,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.GRAPH_EDGES (
  FROM_ID VARCHAR, FROM_NAME VARCHAR, FROM_TYPE VARCHAR, RELATIONSHIP VARCHAR,
  TO_ID VARCHAR, TO_NAME VARCHAR, TO_TYPE VARCHAR, KIND VARCHAR, DETAIL VARCHAR,
  SOURCE VARCHAR, REPORTED_BY VARCHAR, CONFIDENCE VARCHAR, EVIDENCE VARCHAR,
  FILING_URL VARCHAR, NOTE VARCHAR
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.GRAPH_COMPANIES (
  TICKER VARCHAR, NAME VARCHAR, IN_UNIVERSE BOOLEAN, CIK NUMBER,
  SECTOR VARCHAR, HQ_COUNTRY VARCHAR
);
